### PR TITLE
Add support for german localization.

### PR DESCRIPTION
**Pull request by janniklorenz**

### CODE REVIEW

**Comment by janniklorenz** [comment]
#157

**Comment by jackycute** [comment]
Please specify your language code and culture name base on [this](https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx).
Thanks for contribute this 😄

**Comment by janniklorenz** [comment]
It's `de-DE` / `German - Germany` / `0x0407`

**Comment by jackycute** [comment]
Thanks again!

**Pull request merged**
