### PR TITLE
Add compatibility to install on windows and fixed sslcapath bug

### PR DESCRIPTION
**Pull request by laysdra7265**
Add support for windows environment.
and fixed sslcapath bug.
Sorry, I mixed up two pull requests.
It looks like not a right way to pull request

### CODE REVIEW

**Comment by laysdra7265** [comment]
#634

**Comment by SISheogorath** [comment]
Can you please split these fixes into two separated branches?

This way we can't merge it.

**Comment by laysdra7265** [comment]
Ok,I give me some time to split this.

**Comment by SISheogorath** [comment]
Should work with:

```
git branch fix/sslcapath
git reset HEAD~2
git push -f
git checkout fix/sslcapath
git push
```

**Pull request closed without merging**
