### PR TITLE
createdAt DESC with quotation marks did not work with MySQL fixes #565

### LINKED ISSUE #565: History (Version list) unsorted?
When I try to go over recent changes, the list looks like this for me: 

grafik

It appears not to be sorted by anything meaningful. It's not sorted by date, not by size of the document (not that this would make sense).

The Version in use is 0.5.1, running on MySQL.

### PR DESCRIPTION
**Pull request by ccoenen**
This _has_ to be doublechecked with PostgreSQL! I did not yet test that.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Sadly as it turned out, the quotes are needed for PostgreSQL to work. Otherwise, the handling of the column name is case-insensitive and PostgreSQL can't find the column anymore, which breaks the functionality completely.

But using the array syntax (`order: [['createdAt', 'DESC']]`) seems to work.

**Comment by ccoenen** [comment]
How about Backticks? They are used all over the MySQL documentation?

**Comment by ccoenen** [comment]
(Sequelize docs on ordering: http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering )

**Comment by SISheogorath** [comment]
That's for version 4.

We use version 3. See https://sequelize.readthedocs.io/en/v3

**Comment by ccoenen** [comment]
Thanks! http://sequelize.readthedocs.io/en/v3/docs/querying/#ordering

**Comment by ccoenen** [comment]
So. if anyone could take this updated commit for a spin on PostgreSQL, we could probably merge it into master :)

**Pull request merged**
