### PR TITLE
Extend to support GitLab Authentication

### PR DESCRIPTION
**Pull request by jccrofty30**
Commit List:
* Add necessary dependency.
* Add baseURL parameter for self-hosted GitLab
* Add necessary require.
* Add block for GitLab auth.
* Fix typo
* Update font-awesome dependency for GitLab icon.
* Use a color closer to GitLab orange.
* More direct TODO

Focus solely on authentication, saving/opening `snippets` not addressed.

### CODE REVIEW

**Comment by jccrofty30** [comment]
Sorry for open/close/open...wanted to use a more descriptive branch name.

**Comment by jackycute** [comment]
Hi @jccrofty30 !
Thanks for PR, will merge this soon.

**Comment by jccrofty30** [comment]
Sure thing! Glad I could contribute.

**Comment by jccrofty30** [comment]
Fixed merge conflicts resulting from most recent updates.

**Comment by jackycute** [comment]
Only one thing you missed right there, the gitlab avatar for user photo url.
https://github.com/hackmdio/hackmd/blob/master/lib/models/user.js#L54

**Comment by jccrofty30** [comment]
I did indeed. Will address in short-order.

**Comment by jccrofty30** [comment]
Taken care of.

**Pull request merged**
