### PR TITLE
License Change Agreement

### PR DESCRIPTION
**Pull request by jackycute**
We [propose a license change, from **MIT** to **AGPL 3.0**](https://hackmd.io/s/r1_4j9_hZ), for the open source project HackMD Community Edition (CE), and ask for your understanding and agreement.
Please leave a comment below the PR saying: 

**“I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD. 
Signed-off-by:  Full_name <my_real@mail.address>“**

Thank you again for your contribution to the project and the community.
Please let us know if you have any questions.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Time to make this project, even more FOSS and see awesome contributions!

I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Christoph Kern sheogorath@shivering-isles.com

**Comment by ccoenen** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Claudius Coenen opensource@amenthes.de

**Comment by elct9620** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Qiu Zheng Xian contact@frost.tw

**Comment by alecdwm** [comment]
I agree to the change of license from MIT to AGPL on all my past code contributions to the project HackMD.
Signed-off-by: Alec WM firstcontact@owls.io

**Comment by Yukaii** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Yukai Huang nyan@yukaii.tw

**Comment by PeterDaveHello** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Peter Dave Hello hsu@peterdavehello.org

**Comment by jackycute** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Wu Cheng Han jackymaxj@gmail.com

**Comment by bananaappletw** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Chen Wei Bo bananaappletw@gmail.com

**Comment by ColinMaudry** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Colin Maudry colin@maudry.com

**Comment by bd808** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Bryan Davis bd808@bd808.com

---

How will HackMD Enterprise Edition (EE) will be created from an AGPL licensed codebase? With community contributions being made under the AGPLv3 license, the EE derivative will only be allowed to incorporate changes made in the FLOSS project if the EE is itself released under an AGPLv3+ license. The intent of the AGPL is to [force SaaS hosting providers to release their enhancements to FLOSS projects](https://www.gnu.org/licenses/why-affero-gpl.en.html) and prevent open-core derivatives. Is the intent of the https://hackmd.io/ organization to permanently fork their EE version prior to the AGPL license conversion and abandon future FLOSS community contributions?

**Comment by Stonesjtu** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Kaiyu Shi skyisno.1@gmail.com

**Comment by weisslj** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Johannes Weißl jargon@molb.org

**Comment by GitOnion** [comment]
@bd808 Thanks for the question! 
Yes, EE would be (is already) forked from CE before the license change. We will not directly merge/integrate the community contribution to CE going forward, so contributors to CE won't have to worry about your works being taken by us for free and we won't have to worry about some other parties taking the great work of the community to compete with us on commercialization. Which also means, we as a developer team would have to stay ahead of (or at least keep up with) the creativity and productivity of the community. Hopefully we can manage that challenge! 
If we cannot keep up with the community, that means CE has become a great tool in itself by then! Then we would celebrate the success of the community and pride ourselves in initiating the project and devoting it to public good! (And we move on to find jobs, lol)

**Comment by janniklorenz** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Jannik Lorenz dev@janniklorenz.de

**Comment by FlorianRhiem** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Florian Rhiem florian.rhiem@gmail.com

**Comment by xxyy** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Philipp Nowak git@l1t.li
(via https://github.com/hackmdio/hackmd/pull/585#issuecomment-336313817)

**Comment by geekyd** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Dilpreet Singh singhsince94@gmail.com

**Comment by a60814billy** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: BoHong Li (Raccoon) a60814billy@gmail.com (raccoon@hackmd.io)

**Comment by DrMurx** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Jan Kunzmann jan-github@phobia.de

**Comment by felixonmars** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Felix Yan felixonmars@archlinux.org

**Comment by Rwing** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Rwing Liu  rwing@rwing.cn

**Comment by CrazyPython** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: James Lu jamtlu@gmail.com

**Comment by DoubleMalt** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Christoph Witzany christoph@web.crofting.com

**Comment by mosterdt** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Thomas De Backer thomasisdebacker5@gmail.com

**Comment by nakaeeee** [comment]
I agree to the change of license from MIT to AGPL on all my past code contribution to the project HackMD.
Signed-off-by: Norihito Nakae norihito.n@gmail.com

**Comment by jackycute** [comment]
Thank all the contributors here! We couldn't make this without your efforts 👍 
Special thanks to @SISheogorath and @ccoenen for spending tons of time and work for community!

**Review by fitriadi19 — COMMENTED** [review]
Merged agreement

**Comment by ccoenen** [comment]
Is anyone else finding this behaviour odd? This is a seven year old merge. It certainly did not need another review or comment?

**Pull request merged**
