### PR TITLE
Add documentation for setting up authentication with a self-hosted GitLab

### PR DESCRIPTION
**Pull request by mcnesium**

### CODE REVIEW

**Comment by mcnesium** [comment]
Maybe also the different auth providers should be separated to individual files… 🤔

**Comment by SISheogorath** [comment]
I agree that we should split it up in future.

For the first guides I thought it's easier to keep it in one file.

Thanks for your work!

Can you please squash your commits together and sign-off the commit using `git commit --sign-off`?

```
# Mark all unwanted commits as fixup
git rebase -i HEAD~2
# Now sign the new commit of
git commit --amend --sign-off
```

Then we'll merge this :)

**Comment by mcnesium** [comment]
ok I think I managed to do this

**Comment by SISheogorath** [comment]
Well, not completely 😉 But let me help you:

First of all, you have to re-run the rebase command:
```console
git rebase -i HEAD~4
```

Now an editor will open and provide you multiple lines, with commits.

There you replace the word `pick` with `fixup` for all commits apart from the first one. The first one stays as "pick".

Once this is done, write the file and close the editor.

Now you have to sign-off the commit again and push it to GitHub:
```console
git commit --amend --signoff
git push -f
```

I hope this is helpful :) and thanks for your contribution 👍

**Comment by mcnesium** [comment]
next try

**Comment by SISheogorath** [comment]
Sorry that you needed to wait for such a long time. Okay, let's say it as it is, the current commit is completely broken :D

I would recommend you to take your changes, the `auth.md` and the screenshots, copy them into a second directory. Then remove your local repository, delete your fork, re-fork it on GitHub, clone it to your local machine (`git clone git@github.com:mcnesium/hackmd.git`), create a branch (`git checkout -b docs/gitlab`), put your files back in place and create a new commit using `git commit --signoff`. Once this is done, you do a `git push` and re-create the PR here.

Sorry, that it's so complicated but you really broke your entire git history and recovery would probably need way more time :/

Some suggestions for learning more about git:
https://help.github.com/articles/fork-a-repo/
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by mcnesium** [comment]
ok, see #788

**Pull request closed without merging**
