### PR TITLE
Implemented dark theme.

### PR DESCRIPTION
**Pull request by edoardoo**
I've implemented a dark theme feature. 
Thought to share it. 
Also, feedbacks of any kind are highly appreciated.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Awesome work! Can you provide a screenshot of the dark mode?

Also, could you please fix the syntax so the linter doesn't fail anymore?

All in all I like the idea!

/cc #107

**Comment by edoardoo** [comment]
Sure, I just fixed the linter.  
Here is the screenshot:   
screenshot-2017-12-28 features - hackmd

**Comment by edoardoo** [comment]
Having now read the #107, if we think that *Night mode* fits better I'm still in time to change it. 
Also, the icon is a moon so it would made more sense.

**Comment by ccoenen** [comment]
One request, judging from the screenshot: I believe the text should not be plain white. Toning it down slightly may look even better.

**Comment by edoardoo** [comment]
@ccoenen 
For reference: The previous screenshot is with text color `#f2f2f2` and headings color: `#eee`.  
This screenshot is with text as `#ededed` and headings `#ddd`.  
screenshot-2017-12-29 features - hackmd  
  
Also, If you want to test it, I've pushed the edit to an [heroku instance](https://wriwri.herokuapp.com/features). 

In the dev process I've taken as a reference the feature page. Do you think it covers extensively the html generated by the markdown?

**Comment by ccoenen** [comment]
Just looked at it live (thanks!) and I like it a lot!

The Features Page is a very good place to start. I believe it covers most of the things.

Some of the diagrams and the code boxes are not perfect, but I would be okay with merging it regardless. For one thing: this is an improvement, and it does not break anything that has existed before. Also the fine tuning of diagrams / code boxes creates a few simple tickets that may be good starter tickets for new contributors.

**Comment by SISheogorath** [comment]
Can you please squash the commits? And sign-off the commit?

---

## How to do?

### Squash commits:

```console
git rebase -i HEAD~3
```

Now mark all fix commits at `fixup`

### Sign-off commits afterwards

Some information about Signing off commits can be found in our contribution information:

https://github.com/hackmdio/hackmd/blob/master/CONTRIBUTING.md#sign-your-work

```console
git commit --amend --sign-off
```

For even more improvements, feel free to GPG sign your work. Information about that:
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Pull request merged**
