### PR TITLE
added small guide for auth

### PR DESCRIPTION
**Pull request by devonJS**
Added most of the outcomes of the tickets marked `auth provider`, some of the tickets just needed a fix / not-valid.  I couldn't come up with a great bulletpoint for this comment though: https://github.com/hackmdio/hackmd/issues/141#issuecomment-261320228, wasn't sure how the`domain` property is completely used.

Any suggestions to improving is welcome!  I could've missed a few points for sure.

### CODE REVIEW

**Comment by SISheogorath** [comment]
Thanks a lot for this guide!

Could you add a basic description of "What to do, to setup HackMD with provider XY"?

Some kind of step by step guide for a provider of your choice :)

**Comment by devonJS** [comment]
@SISheogorath updated! added couple things to the README and config.json.example to include some s3 information as well

**Comment by SISheogorath** [comment]
To be honest I'm not the biggest fan of these changes.

The `README.md` and the `config.json.example` are fine, but the description for the configs is a bit too much copy and paste.

Let me explain what I expect because that probably caused some confusion.

We talk about the guide section, so we should guide new users to an auth provider.

Let's take GitHub as an example:

---

GitHub
---

First of all, you need to sign up for a GitHub Account yourself and sign in to GitHub.

Once that is done, check the [OAuth section in the Developer Settings](https://github.com/settings/developers).

Create a new OAuth App:
image

Provide app name, [callback URL](https://github.com/hackmdio/hackmd#third-party-integration-oauth-callback-urls) and Homepage of your organization:
image

*Note: The callback URL is `<your-hackmd-url>/auth/github/callback`*

After registering the application, you get the Client ID and the Client Secret.

image

*Hint: Make your application more attractive by adding your organization's logo as app logo*

Put them into your `config.json`:

```
{
  "production": {
      ...
      "github": {
        "clientID": "3747d30eaccXXXXXXXXX",
        "clientSecret": "2a8e682948eee0c580XXXXXXXXXXXXXXXXXXXXXX"
      },
      ...
  }
}
```

OR

as environment variables on startup:

```
HMD_GITHUB_CLIENTID=3747d30eaccXXXXXXXXX
HMD_GITHUB_CLIENTSECRET=2a8e682948eee0c580XXXXXXXXXXXXXXXXXXXXXX
```

Restart HackMD and you can **sign in using GitHub**!

---

I know this is a lot of work and this guide took me 20-30 minutes. But I don't expect to get all at once. It would be nice to get them one by one (of course you are also welcome to do them all ^^) but I think we should try to make it as easy as possible for people to adopt this.

I hope this is not too much and you understand what is the goal. 😄 

Cheers

**Comment by devonJS** [comment]
@SISheogorath apologies for the misunderstanding! thanks for providing an example, definitely is more clear of what you're looking for.  will get something back up later this week / early next week.

**Comment by SISheogorath** [comment]
You can add the GitHub guide (feel free to extend it) as your work and add maybe another provider, too.

To make it a bit easier I'll provide you the sources for the GitHub guide: https://hackmd.io/IYFg7AJgnARgZgJgLQEYRwMZJDAzLpYFCA6GUXAUwAYBWADmtyA=#

**Comment by devonJS** [comment]
@SISheogorath updated for GitHub and Twitter docs

**Comment by SISheogorath** [comment]
Awesome @devonJS! Can we remove the non-verbose guides?

With this done, we can merge it :)

**Comment by devonJS** [comment]
@SISheogorath updated!

**Comment by SISheogorath** [comment]
Thanks a lot!

**Pull request merged**
