### PR TITLE
Allow posting new note with content

### PR DESCRIPTION
**Pull request by fooker**
This allows to specify initial content while creating a new note.

### CODE REVIEW

**Comment by ccoenen** [comment]
Interesting! Can you give an example on when you use this? And perhaps an example of how you use it?

**Comment by fooker** [comment]
We would like to use hackmd for filling protocols of regular meetings. Using this, we preseed the per-meeting note with a protocol template and publish it to the participants. We're planing to do this with an IRC bot, but it is a hacky shell script right now. It basicly does something like this:
```
curl -v -XPOST -H 'Content-Type: text/markdown' 'http://localhost:3000/new' -d @template.md
```

**Comment by SISheogorath** [comment]
Nice work!

Could you please sign-off the commit?

https://github.com/hackmdio/hackmd/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by fooker** [comment]
Sure. Updated...

**Comment by SISheogorath** [comment]
Needs some docs on the Features page.

Thanks for your contribution! 👍

**Comment by rmst** [comment]
Hi is it possible to use this on hackmd.io ? I tried

```bash
curl -v -XPOST -H 'Content-Type: text/markdown' 'https://hackmd.io/new' -d test123
```
and got back
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /new</pre>
</body>
</html>
```

**Comment by SISheogorath** [comment]
@rmst No, this was after the split between HackMD EE/HackMD.io and CodiMD (former HackMD CE), so it never got there.

**Comment by rmst** [comment]
Oh right, I've made that mistake before.. github.com/hackmdio just looks soo much like it belongs to hackmd.io.
So I found https://notes.ethereum.org and the curl worked, so I suppose that's the official site where CodiML is hosted? Is there a place where I could read up on the story of CodiMD and hackmd.io etc?

I have to say both are stunningly similar. The only functional differences I've noted so far are:
- hackmd.io has link-autocomplete
- notes.ethereum.org has this 'API' for inserting content into new notes.
Are there any other functional differences?

**Comment by SISheogorath** [comment]
We have actually nothing to do with https://notes.ethereum.org/ besides the fact that they happen to run an instance of CodiMD

CodiMD has no official hosted instance. There is https://hackmd-ce.herokuapp.com which is our test/demo instance which runs the latest master.

We recommend to self-host your instance if you want to use CodiMD. We also have an upcoming community call on sunday, if you want to meet some community members (see #911).

About the HackMD vs CodiMD story: Please check #720 and the "TL;DR" in our readme: https://github.com/hackmdio/codimd#hackmd-ce-became-codimd

**Comment by rmst** [comment]
Oh interesting! Thanks for giving me all that info despite this being so off topic!

**Comment by patcon** [comment]
Fwiw, seems to not work on notes.ethereum.org anymore :man_shrugging:

**Comment by SISheogorath** [comment]
@patcon seems like they setup a SaaS instance by the HackMD team. This doesn't support this feature.

**Pull request merged**
