### PR TITLE
Add ability to configure API request scope. Fixes #301

### LINKED ISSUE #301: GitLab OAuth requests too much permissions
When logging in to HackMD via GitLab, the latter tells me the requested scope is too broad, as I am an admin. How could one request a smaller scope, which only receives what is needed from a user?

### PR DESCRIPTION
**Pull request by SISheogorath**
See https://github.com/fh1ch/passport-gitlab2/blob/master/lib/strategy.js#L46

### CODE REVIEW

**Comment by SISheogorath** [comment]
Please notice: untested

**Comment by SISheogorath** [comment]
This should not effect any existing setup. As it only changes new config files generated from the `config.json.example` file.

As the default setting of the upstream plugin is to use `api` all already existing configs will continue as they already work. But improves security for new configs as it limits the authentication to the new `read_user` scope added in [8.15](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5951)

**Comment by jackycute** [comment]
Hi @SISheogorath ,
Thanks for helping this out.
But I don't know if this is ok because we have ability to import/export snippet to gitlab and that might need api scope permission.

**Comment by jackycute** [comment]
I think we could add option for gitlab snippet import/export feature.
And we could set the scope based on that option.

**Comment by jackycute** [comment]
[Fix gitlab request permission by config](https://trello.com/c/5u6ay7od/6-fix-gitlab-request-permission-by-config)

**Comment by jackycute** [comment]
Thanks @SISheogorath 
Fixed in 506a381eca5e2bdc31d3529ecd3f1f7797551406

**Pull request closed without merging**
