### PR TITLE
Turn grey to a darker eigengrau

### PR DESCRIPTION
**Pull request by CrazyPython**
In my complete opinion, this looks better. [Eigengrau](https://en.wikipedia.org/wiki/Eigengrau) has slightly more blue than red and green.

### CODE REVIEW

**Comment by jackycute** [comment]
Hi @CrazyPython 
Below are my personal opinions.
1. This is a very deep "grey".
2. But it does have better contrast.
3. It change the theme color tone.

**Comment by jackycute** [comment]
I'm curious about your "complete opinion", could you tell more?

**Comment by CrazyPython** [comment]
Well, greys with a tint of blue usually look better. Looking back, I should use a lighter shade of eingengrau. I'll remind myself to change that.

**Comment by MartB** [comment]
+1

**Comment by SISheogorath** [comment]
@CrazyPython can you provide some screenshots for this pull request, so we can see the difference? Would make it way easier to decide. Thanks~

**Comment by ccoenen** [comment]
Closing this PR, since it has been half a year with no activity. If you get back to it, there's no reason not to merge it! I'm not against this change, I just got the feeling that it was unfinished.

**Pull request closed without merging**
