### PR TITLE
Add jsonlint script to ensure all json files are valid

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Wanna add one more test  :)

### CODE REVIEW

**Comment by SISheogorath** [comment]
How about having a look at code climate?

it should allow all these kinds of testing :) I played around with it here:
https://github.com/sisheogorath/hackmd/tree/qa/codeclimate

You are very welcome to extend and make it usable 😄

**Comment by PeterDaveHello** [comment]
Looks cool, but I may need some time to learn about it, looks like the branch needs more tuning to be ready? If I'm not wrong, maybe migrate to code climate then? Let me know what do you think, thanks!

**Comment by SISheogorath** [comment]
Mhm maybe it's not the worst idea, to add this PR right now and introducing codeclimate later since it will need a lot of work and as it'll touch almost all files, I would like to do it after the AGPL change.

---

For this PR 👍  We should add this. Can you add it to the test command as well, so we validate both using travis?

**Comment by PeterDaveHello** [comment]
@SISheogorath sorry that i didn't propose first, I have another branch to refactor the Travis CI build:
https://github.com/PeterDaveHello/hackmd/tree/refactor-TravisCI-config

which will introduce matrix syntax and than add multiple tests in(not mean to earn many commits, I add them all in a single one), since current one needs few tuning, so that I didn't do it all together, would that be great for you?

**Comment by SISheogorath** [comment]
i was referring to this test command:

https://github.com/hackmdio/hackmd/blob/53c2d0b5ca5901c1d1cad819e2049b16fba18ea8/package.json#L7

:+1: for the Travis refactoring

**Comment by PeterDaveHello** [comment]
You mean to combine it like  `"test": "npm run-script standard && npm run-script jsonlint", `? I wonder if it'll be too long and mixed with too many things especially if we're going to add more tests?

**Comment by SISheogorath** [comment]
Yes, that's what I meant.

We will probably move it to a more useful place later but for now, I think that's the place to go.

**Comment by PeterDaveHello** [comment]
Done.

**Pull request merged**
