### PR TITLE
修正權限敘述 (Enhance permission description)

### PR DESCRIPTION
**Pull request by alan23273850**
開發團隊您好：
　　我今天嘗試著將我的 hackmd 發布出去，結果對方 (guests) 只看到 403 forbidden 的畫面，我後來嘗試了一下才發現原來 forbid guests 的權限包含讀跟寫，我原先以為只有寫，所以想說把這邊的敘述改一下比較好。因為這只是算是小事，就直接請求 pull requests 等待您們同意。如果您們想做其他修正的話，也可自行修正，同時關閉我的 pull requests，謝謝！

-------------------------------------------------------------------------------------

　　I have modified some descriptions of permission selection for this pull request, because the original meaning of the description is unclear about guests. I originally thought that the term (forbid guests) only takes effect on editing, but in fact it takes effect on both editing and **viewing**. Therefore I have made this change. Thank you!

### CODE REVIEW

**Comment by jackycute** [comment]
Thanks for providing this PR @alan23273850 

Those description of permissions were abbreviated since the UI space is limited.
But we will consider that again.

**Comment by SISheogorath** [comment]
I agree that the permission descriptions are not perfect, but I think from a UI perspective it's currently better than the extended version.

We should find another place where we simply explain the permissions more detailed.

Draft for such a documentation: https://hackmd.io/EwNg7CIBwGYwtFARgQwCbwCwE4bfktgMYICmRADAMywCMYKFYYQA#

**Comment by ccoenen** [comment]
I added the same table, but ordered from MOST to LEAST privileges, I think it makes the table easier to parse visually.

**Comment by SISheogorath** [comment]
@ccoenen  I knew I saw it somewhere xD But couldn't find it instantly so I made and own one 👍 We should put it into the [features.md](https://github.com/hackmdio/hackmd/blob/master/public/docs/features.md). Do you want to file a PR for that or should I?

**Comment by SISheogorath** [comment]
Closing this PR for now in favor of #569 since UI space is limited.

**Comment by SISheogorath** [comment]
Thanks a lot for your work @alan23273850!

**Pull request closed without merging**
