### PR TITLE
Added Swedish translation

### PR DESCRIPTION
**Pull request by kajes**

### CODE REVIEW

**Comment by jackycute** [comment]
Thank you @kajes !
Could put on your language code and culture name based on #157 ?

**Comment by kajes** [comment]
Sure, I'll do it right now.

**Comment by jackycute** [comment]
Actually I mean you look up the name and comment here.
Anyway, thanks again.

**Comment by kajes** [comment]
Haha, ok, didn't quite get that, but it was just simpler to add it myself since I know it by heart anyway ;)

**Pull request merged**
